MODULES    := Dependent Arithmetic0 Arithmetic1 Data0 Data1 Lambda0 Lambda1 Lambda2 Imp0 Imp1 Imp2 ImpTemplate
VS         := $(MODULES:%=%.v)

.PHONY: coq clean

coq: Makefile.coq
	$(MAKE) -f Makefile.coq

Makefile.coq: Makefile $(VS)
	coq_makefile $(VS) -o Makefile.coq

clean:: Makefile.coq
	$(MAKE) -f Makefile.coq clean
	rm -f Makefile.coq
